// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjuWvSbjeas-qYjy7-B_pbUTjnLqLjMvs',
    appId: '1:218965388878:web:63081ab8eb79a8e4f09d1f',
    messagingSenderId: '218965388878',
    projectId: 'zmaker-6c602',
    authDomain: 'zmaker-6c602.firebaseapp.com',
    storageBucket: 'zmaker-6c602.firebasestorage.app',
    measurementId: 'G-5YN24424G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGLQXZlY76A4RjaycV76kHdbW8W7CzFDs',
    appId: '1:218965388878:android:3d1593a65feb2ab0f09d1f',
    messagingSenderId: '218965388878',
    projectId: 'zmaker-6c602',
    storageBucket: 'zmaker-6c602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4E_drgb07zqVbB-u1kvOldx8nCaSLBGM',
    appId: '1:218965388878:ios:07f3a2412ae055aaf09d1f',
    messagingSenderId: '218965388878',
    projectId: 'zmaker-6c602',
    storageBucket: 'zmaker-6c602.firebasestorage.app',
    iosClientId: '218965388878-3qp1e3lr2hmd991pa80menhor23e90op.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4E_drgb07zqVbB-u1kvOldx8nCaSLBGM',
    appId: '1:218965388878:ios:07f3a2412ae055aaf09d1f',
    messagingSenderId: '218965388878',
    projectId: 'zmaker-6c602',
    storageBucket: 'zmaker-6c602.firebasestorage.app',
    iosClientId: '218965388878-3qp1e3lr2hmd991pa80menhor23e90op.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjuWvSbjeas-qYjy7-B_pbUTjnLqLjMvs',
    appId: '1:218965388878:web:3bffbeda73b894c8f09d1f',
    messagingSenderId: '218965388878',
    projectId: 'zmaker-6c602',
    authDomain: 'zmaker-6c602.firebaseapp.com',
    storageBucket: 'zmaker-6c602.firebasestorage.app',
    measurementId: 'G-E564QHT866',
  );

}